site_name: optics-ts
site_url: https://akheron.github.io/optics-ts
repo_url: https://github.com/akheron/optics-ts
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: '#'
nav:
  - Home: 'index.md'
  - 'installation.md'
  - 'tutorial.md'
  - 'apiref.md'
  - 'two-syntaxes.md'
  - 'prior-art.md'
